### ISSUE TITLE
Migrate to couchDB

### ISSUE THREAD

**Issue by ribalba** [eHealthAfrica/Amsel#1]
Currently we are using a relational database. This was due to the fact that we needed a woking prototype very fast and Django has native support for such a DB. We need the patient data to be saved and updated in a couchDB. A simplified schema should look like [1]. The mapping (from the post we get from formhub) is:

- uid is generated and is saved under otherIds (see eval_json in eval_methods.py)
- first_name => surname
- last_name => otherNames
- enter_number => Needs to be added to the schema as health worker contact 
- caregiver_number => Needs to be added to the schema as caregiver (family member)
- age => age
- geolocation => currentLocation 

## [1] 
     {
       "type": "object",
       "properties": {
     
         "doc_type": { "type": "string", "pattern": "^person$" },
     
         "version": { "type": "string", "format": "semver" },
     
         "referenceNumber": { "type": "integer" },
     
         "otherIds": { "type": "object" },
     
         "surname": { "type": "string", "minLength": 1 },
         "otherNames": { "type": "string" },
     
         "occupation": { "type": "string" },
     
         "age": { "type": "number" },
         "gender": { "enum": ["m", "f"] },
         "status": { "enum": ["alive", "dead"] },
     
         "classification": { "enum": ["case", "contact"] },
         "subClassification": { "type": "string" },
     
         "currentLocation": { "type": "string" },
     
         "phoneNumber": { "type": "string" },
         "phoneOwner": { "type": "string" },
     
         "address": { "$ref": "#/definitions/address" },
     
         "createdDate": { "type": "string", "format": "date-time" },
         "modifiedDate": { "type": "string", "format": "date-time" },
     
         "changeLog": { "$ref": "#/definitions/changeLog" },
     
     
         "actions": { "type": "array" },
     
         "comments": { "type": "array", "items": {
             "type": "object",
             "properties": {
               "date": { "type": "string", "format": "date-time" },
               "text": { "type": "string" }
             }
           }
         },
     
         "source": { "type": "object" }
       },
     
       "definitions": {
     
         "address": { "type": "object", "additionalProperties": {
           "type": ["string", "integer"]
         }},
     
     
         "changeLog": { "type": "array", "items": {
           "type": "object",
           "properties": {
             "rev": { "type": "string" },
             "timestamp": { "type": "integer" },
             "user": { "type": "string" }
           }
         }},
     
       "required": [
         "doc_type",
         "version",
         "surname",
         "classification"
       ]
     }

**Comment by lucychambers** [comment]
Won't do
