### ISSUE TITLE
Android App to enable data entry 

### ISSUE THREAD

**Issue by ribalba** [eHealthAfrica/Amsel#2]
We are currently using ODK for data entry. While this is totally sufficient it would be really useful to have an app that caregivers can use to add this data and this is directly added to the CouchDB. Important properties for the first version are:

- Offline first. Internet is really bad in some areas. All data needs to be cached and uploaded when online
- Easy to use and clear instructions
- Must work on small screens 
- The person using the phone should enter database credentials and his now only once

Please look at the formhub form for the fields. You will probably also need to modify the django side to receive your data or push to couch directly (pouchDB can not be used do to the data size).

**Comment by lucychambers** [comment]
My understanding from Didi is that this is no longer required as most registrations are done via computer in the ETUs and not really out in the field. Closing for now. Will re-open if we get contradictory information.
