### ISSUE TITLE
App to change the status of a patient

### ISSUE THREAD

**Issue by ribalba** [eHealthAfrica/Amsel#4]
For people to use the system it is vital that it is very easy to update the status of a patient. We need an easy to use android app so health care workers can easily search for a patient and then update his current location and if he is alive/dead. Search should be possible on:

- name
- id

Once the patient is found it should be possible to update

- location
- alive/dead
- add comment

This is system also needs to work on a computer in a browser.

**Comment by lucychambers** [comment]
Won't fix - do most of this via comp
